(function(){
'use strict';
const SUPABASE_URL='https://lsnmcdzupctwizxldjhc.supabase.co';
const SUPABASE_KEY='sb_publishable_iJQ9BpS19OtdaYXM31J3ag_Mhljn8Xi';
const OWNER_TABLE='owner_data';
const OWNER_EMAIL='1987zinwaimin@gmail.com';
const OWNER_INTENT_KEY='salary_owner_login_intent';
let sb=null;
function ensureSupabase(){if(window.supabase&&window.supabase.createClient){if(!sb)sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return sb}return null}
function loadSupabase(){if(document.getElementById('supabaseOwnerSdk'))return;const s=document.createElement('script');s.id='supabaseOwnerSdk';s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.async=true;s.onload=()=>ensureSupabase();document.head.appendChild(s)}
function style(){if(document.getElementById('ownerDataStyle'))return;const s=document.createElement('style');s.id='ownerDataStyle';s.textContent='.ownerBtn{background:linear-gradient(135deg,#fff7e8,#fff)!important;border:1px solid #f1dfb5!important}.ownerCard{background:#fff;border-radius:22px;padding:18px;box-shadow:0 12px 30px #34217a14}.ownerAvatar{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#f0eaff;font-size:28px;margin:auto}.ownerField{width:100%;padding:13px;border:1px solid #dfe3ef;border-radius:13px;background:#fff;outline:0;margin-top:10px;box-sizing:border-box;font-size:16px}.ownerBtnMain{width:100%;padding:13px;border:0;border-radius:13px;background:linear-gradient(135deg,#6948ff,#9a4dff);color:#fff;font-weight:800;margin-top:10px}.ownerBtnAlt{width:100%;padding:12px;border:1px solid #d8dcef;border-radius:13px;background:#fff;color:#5946c7;font-weight:800;margin-top:9px}.ownerHint{font-size:11px;color:#71809a;line-height:1.45;text-align:center}.ownerSuccess{padding:10px;border-radius:12px;background:#e8f8f0;color:#16805a;font-size:12px;font-weight:700;margin-top:9px;text-align:center}.ownerError{padding:10px;border-radius:12px;background:#ffe7eb;color:#d83d54;font-size:12px;font-weight:700;margin-top:9px;text-align:center}.ownerTabs{display:flex;gap:8px;margin:12px 0}.ownerTab{flex:1;padding:10px;border:1px solid #ddd;border-radius:12px;background:#fff;font-weight:800;color:#64748b}.ownerTab.active{background:#eee9ff;border-color:#9a7cff;color:#6045d8}';document.head.appendChild(s)}
function closeOwnerData(){const m=document.getElementById('modal');if(m){m.classList.add('hidden');m.innerHTML=''}}
function showMsg(html){const x=document.getElementById('ownerLoginMsg');if(x)x.innerHTML=html}
function switchOwnerMode(mode){const reg=mode==='register';document.getElementById('ownerRegisterBox').style.display=reg?'block':'none';document.getElementById('ownerLoginBox').style.display=reg?'none':'block';document.getElementById('ownerTabReg').classList.toggle('active',reg);document.getElementById('ownerTabLogin').classList.toggle('active',!reg);showMsg('')}
async function ownerRegister(){try{const c=ensureSupabase();if(!c){showMsg('<div class="ownerError">❌ Cloud service မတက်သေးပါ။ ခဏစောင့်ပြီး ပြန်စမ်းပါ။</div>');return}const email=String(document.getElementById('ownerEmailInput')?.value||'').trim().toLowerCase();const p=String(document.getElementById('ownerPasswordInput')?.value||'');const cp=String(document.getElementById('ownerPasswordConfirm')?.value||'');if(email!==OWNER_EMAIL){showMsg('<div class="ownerError">❌ ဒီ Gmail ကို Owner အဖြစ် သတ်မှတ်ထားတာ မဟုတ်ပါ။</div>');return}if(p.length<6){showMsg('<div class="ownerError">❌ Password အနည်းဆုံး 6 လုံး ထည့်ပါ။</div>');return}if(p!==cp){showMsg('<div class="ownerError">❌ Password နှစ်ခု မတူပါ။</div>');return}showMsg('⏳ Owner Register လုပ်နေသည်...');const {data,error}=await c.auth.signUp({email,password:p,options:{emailRedirectTo:location.origin+location.pathname}});if(error){const em=String(error.message||'').toLowerCase();if(em.includes('already registered')||em.includes('already exists')){showMsg('<div class="ownerError">⚠️ ဒီ Gmail နဲ့ Account ရှိပြီးသားပါ။ Register မလိုတော့ပါ။ Gmail Verify လုပ်ပြီး Login ကိုရွေးပါ။</div>');switchOwnerMode('login');return}throw error}if(data?.user){if(data.session){await c.auth.signOut()}showMsg('<div class="ownerSuccess">📧 Register အောင်မြင်ပါပြီ။ Gmail ထဲက Verification ကိုနှိပ်ပြီးမှ Login ဝင်ပါ။</div>');setTimeout(()=>switchOwnerMode('login'),700)}}catch(e){showMsg('<div class="ownerError">❌ Register မအောင်မြင်ပါ။ Gmail/Password ကိုစစ်ပြီး ပြန်စမ်းပါ။</div>')}}
async function ownerPasswordLogin(){try{const c=ensureSupabase();if(!c){showMsg('<div class="ownerError">❌ Cloud service မတက်သေးပါ။</div>');return}const email=String(document.getElementById('ownerEmailInput')?.value||'').trim().toLowerCase();const password=String(document.getElementById('ownerPasswordInput')?.value||'');if(email!==OWNER_EMAIL){showMsg('<div class="ownerError">❌ Owner Gmail မမှန်ပါ။</div>');return}if(!password){showMsg('<div class="ownerError">❌ Owner Password ထည့်ပါ။</div>');return}showMsg('⏳ Owner Login စစ်နေသည်...');const {data,error}=await c.auth.signInWithPassword({email,password});if(error||!data?.user){if(String(error?.message||'').toLowerCase().includes('email not confirmed')){showMsg('<div class="ownerError">📧 Gmail ကို အရင် Verify လုပ်ပါ။ ပြီးရင် Login ဝင်ပါ။</div>');return}showMsg('<div class="ownerError">❌ Gmail သို့မဟုတ် Password မမှန်ပါ။</div>');return}sessionStorage.setItem(OWNER_INTENT_KEY,'1');try{const meta=data.user.user_metadata||{};await c.from(OWNER_TABLE).upsert({user_id:data.user.id,owner_name:meta.full_name||meta.name||'Owner',owner_email:OWNER_EMAIL,avatar_url:meta.avatar_url||meta.picture||'',updated_at:new Date().toISOString()},{onConflict:'user_id'})}catch(e){}showMsg('<div class="ownerSuccess">✅ Owner Login အောင်မြင်ပါပြီ။</div>');setTimeout(()=>closeOwnerData(),500)}catch(e){showMsg('<div class="ownerError">❌ Owner Login မအောင်မြင်ပါ။</div>')}}
async function resendOwnerVerification(){try{const c=ensureSupabase();const email=String(document.getElementById('ownerEmailInput')?.value||'').trim().toLowerCase();if(email!==OWNER_EMAIL){showMsg('<div class="ownerError">❌ Owner Gmail မမှန်ပါ။</div>');return}const {error}=await c.auth.resend({type:'signup',email:OWNER_EMAIL,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;showMsg('<div class="ownerSuccess">📧 Verification Email ပြန်ပို့ပြီးပါပြီ။ Gmail ထဲက Verify လုပ်ပြီး Login ဝင်ပါ။</div>')}catch(e){showMsg('<div class="ownerError">❌ Verification Email မပို့နိုင်သေးပါ။ ခဏစောင့်ပြီး ပြန်စမ်းပါ။</div>')}}
function openOwnerData(){const m=document.getElementById('modal');if(!m)return;m.className='modal';m.classList.remove('hidden');m.innerHTML='<div class="sheet"><div class="sheethead"><h2>👑 Owner Data</h2><button class="close" onclick="closeOwnerData()">×</button></div><div class="ownerCard"><div class="ownerAvatar">👤</div><div style="font-weight:800;text-align:center;margin:8px 0;font-size:20px">Owner Account</div><div class="ownerHint">Gmail နဲ့ အရင် Register လုပ်ပြီး Gmail Verification ပြီးမှ Login ဝင်ပါ။ Link ရုံနဲ့ Auto Login မလုပ်ပါ။</div><div class="ownerTabs"><button id="ownerTabReg" class="ownerTab active" onclick="switchOwnerMode(\'register\')">📝 Register</button><button id="ownerTabLogin" class="ownerTab" onclick="switchOwnerMode(\'login\')">🔐 Login</button></div><input id="ownerEmailInput" class="ownerField" type="email" autocomplete="username" placeholder="Owner Gmail"><div id="ownerRegisterBox"><input id="ownerPasswordInput" class="ownerField" type="password" autocomplete="new-password" placeholder="Password"><input id="ownerPasswordConfirm" class="ownerField" type="password" autocomplete="new-password" placeholder="Confirm Password"><button class="ownerBtnMain" onclick="ownerRegister()">📝 Owner Register</button><button class="ownerBtnAlt" onclick="resendOwnerVerification()">📧 Gmail Verification ပြန်ပို့ရန်</button></div><div id="ownerLoginBox" style="display:none"><input id="ownerPasswordInputLogin" class="ownerField" type="password" autocomplete="current-password" placeholder="Owner Password"><button class="ownerBtnMain" onclick="ownerPasswordLogin()">🔐 Owner Login</button></div><div id="ownerLoginMsg" class="ownerHint" style="margin-top:10px"></div></div></div>'}
function addMenu(){const drawer=document.querySelector('.drawer');if(!drawer||drawer.dataset.ownerReady)return;const b=document.createElement('button');b.className='mi ownerBtn';b.type='button';b.innerHTML='👑 Owner Data';b.onclick=function(){if(typeof closeMenu==='function')closeMenu();openOwnerData()};drawer.insertBefore(b,drawer.lastElementChild);drawer.dataset.ownerReady='1'}
function boot(){style();loadSupabase();addMenu();const menu=document.getElementById('menu');if(menu)new MutationObserver(()=>setTimeout(addMenu,0)).observe(menu,{childList:true,subtree:true})}
window.openOwnerData=openOwnerData;window.closeOwnerData=closeOwnerData;window.ownerPasswordLogin=function(){const p=document.getElementById('ownerPasswordInputLogin');if(p){const old=document.getElementById('ownerPasswordInput');if(old)old.value=p.value}return ownerPasswordLogin()};window.ownerRegister=ownerRegister;window.resendOwnerVerification=resendOwnerVerification;window.switchOwnerMode=switchOwnerMode;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
