(function(){
'use strict';
const SUPABASE_URL='https://lsnmcdzupctwizxldjhc.supabase.co';
const SUPABASE_KEY='sb_publishable_iJQ9BpS19OtdaYXM31J3ag_Mhljn8Xi';
const OWNER_TABLE='owner_data';
const OWNER_EMAIL='1987zinwaimin@gmail.com';
const OWNER_INTENT_KEY='salary_owner_login_intent';
let sb=null;
let sdkPromise=null;
function ensureSupabase(){if(window.supabase&&window.supabase.createClient){if(!sb)sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'salary_owner_supabase_auth'}});return sb}return null}
function loadSupabase(){if(ensureSupabase())return Promise.resolve(sb);if(sdkPromise)return sdkPromise;sdkPromise=new Promise((resolve,reject)=>{let s=document.getElementById('supabaseOwnerSdk');if(!s){s=document.createElement('script');s.id='supabaseOwnerSdk';s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.async=true;document.head.appendChild(s)}s.addEventListener('load',()=>{const c=ensureSupabase();c?resolve(c):reject(new Error('Supabase SDK unavailable'))},{once:true});s.addEventListener('error',()=>reject(new Error('Supabase SDK load failed')),{once:true})});return sdkPromise}
function loadLiveShare(){if(document.getElementById('salaryLiveShareScript'))return;const s=document.createElement('script');s.id='salaryLiveShareScript';s.src='share.js?v=live3';s.async=true;document.head.appendChild(s)}
function loadEnhancements(){if(document.getElementById('salaryEnhancementScript'))return;const s=document.createElement('script');s.id='salaryEnhancementScript';s.src='salary-enhancements.js?v=20260826-3';s.async=false;s.onload=()=>{if(document.getElementById('salaryEnhancementFixScript'))return;const f=document.createElement('script');f.id='salaryEnhancementFixScript';f.src='salary-enhancement-fix.js?v=20260826-3';f.async=false;document.head.appendChild(f)};document.head.appendChild(s)}
function loadViewNotifications(){if(document.getElementById('salaryOwnerViewNotifyScript'))return;const s=document.createElement('script');s.id='salaryOwnerViewNotifyScript';s.src='owner-view-notifications.js?v=20260826-3';s.async=true;document.head.appendChild(s)}
function loadOwnerNotificationRepair(){if(document.getElementById('salaryOwnerNotificationRepairV2'))return;const s=document.createElement('script');s.id='salaryOwnerNotificationRepairV2';s.src='owner-notification-repair-v2.js?v=20260827-2';s.async=true;document.head.appendChild(s)}
function redirectUrl(){return location.origin+location.pathname}
function style(){if(document.getElementById('ownerDataStyle'))return;const s=document.createElement('style');s.id='ownerDataStyle';s.textContent=`.ownerBtn{background:linear-gradient(135deg,#fff7e8,#fff)!important;border:1px solid #f1dfb5!important}.ownerCard{background:#fff;border-radius:22px;padding:18px;box-shadow:0 12px 30px #34217a14}.ownerAvatar{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#f0eaff;font-size:28px;margin:auto}.ownerHint{font-size:11px;color:#71809a;line-height:1.45;text-align:center}.ownerGoogle{width:100%;padding:14px 16px;border:1px solid #d8dcef;border-radius:14px;background:#fff;color:#1f2937;font-weight:800;font-size:16px;margin-top:14px;display:flex;align-items:center;justify-content:center;gap:10px;cursor:pointer;box-sizing:border-box}.ownerGoogle:active{transform:scale(.99)}.ownerSuccess{padding:10px;border-radius:12px;background:#e8f8f0;color:#16805a;font-size:12px;font-weight:700;margin-top:10px;text-align:center}.ownerError{padding:10px;border-radius:12px;background:#ffe7eb;color:#d83d54;font-size:12px;font-weight:700;margin-top:10px;text-align:center}.ownerWait{padding:10px;border-radius:12px;background:#fff7df;color:#9a6b00;font-size:12px;font-weight:700;margin-top:10px;text-align:center}.ownerLogged{padding:12px;border-radius:14px;background:#e8f8f0;color:#16805a;margin-top:12px;text-align:center;font-weight:800;font-size:13px}.ownerLogout{width:100%;padding:11px;border-radius:13px;background:#ffe7eb;color:#d83d54;font-weight:800;margin-top:10px}`;document.head.appendChild(s)}
function removeRequestedHelperText(){const exact=['Attendance ထဲမှာပဲ လစာသတ်မှတ်နိုင်ပါတယ်','ချေးငွေယူသူအမည်ကိုနှိပ်ပြီး ချေးငွေအမျိုးအစားများကိုကြည့်ပါ','အကြွေးစာရင်းကို အပေါ်မှာ အရင်ကြည့်ရန်'];document.querySelectorAll('.pageTitle p').forEach(el=>{if(exact.includes(el.textContent.trim()))el.remove()});document.querySelectorAll('label').forEach(el=>{if(el.textContent.trim()==='လစာကာလ')el.remove()})}
function startTextCleaner(){removeRequestedHelperText();if(window.__salaryTextCleaner)return;window.__salaryTextCleaner=new MutationObserver(()=>removeRequestedHelperText());window.__salaryTextCleaner.observe(document.body,{childList:true,subtree:true})}
function closeOwnerData(){const m=document.getElementById('modal');if(m){m.classList.add('hidden');m.innerHTML=''}}
function showMsg(html){const x=document.getElementById('ownerLoginMsg');if(x)x.innerHTML=html}
function waitMsg(t){showMsg('<div class="ownerWait">⏳ '+t+'</div>')}
async function ownerLogout(){try{const c=await loadSupabase();await c.auth.signOut()}catch(e){}sessionStorage.removeItem(OWNER_INTENT_KEY);closeOwnerData()}
async function handleOwnerOAuthReturn(){try{const c=await loadSupabase();const {data:{session}}=await c.auth.getSession();if(!session?.user)return false;const email=String(session.user.email||'').trim().toLowerCase();if(email!==OWNER_EMAIL){await c.auth.signOut();sessionStorage.removeItem(OWNER_INTENT_KEY);return false}sessionStorage.setItem(OWNER_INTENT_KEY,'1');try{const meta=session.user.user_metadata||{};await c.from(OWNER_TABLE).upsert({user_id:session.user.id,owner_name:meta.full_name||meta.name||'Owner',owner_email:email,avatar_url:meta.avatar_url||meta.picture||'',updated_at:new Date().toISOString()},{onConflict:'user_id'})}catch(e){}return true}catch(e){return false}}
async function ownerGoogleLogin(){try{const c=await loadSupabase();waitMsg('Google Login ဖွင့်နေသည်...');const {error}=await c.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirectUrl(),queryParams:{prompt:'select_account'}}});if(error)throw error}catch(e){showMsg('<div class="ownerError">❌ Google Login မဖွင့်နိုင်သေးပါ။</div>')}}
async function openOwnerData(){const m=document.getElementById('modal');if(!m)return;m.className='modal';m.classList.remove('hidden');m.innerHTML=`<div class="sheet"><div class="sheethead"><h2>👑 Owner Data</h2><button class="close" onclick="closeOwnerData()">×</button></div><div id="ownerPanel" class="ownerCard"><div class="ownerAvatar">👤</div><div style="font-weight:800;text-align:center;margin:8px 0;font-size:20px">Owner Account</div><div id="ownerLoginMsg" class="ownerHint" style="margin-top:10px"></div></div></div>`;try{const c=await loadSupabase();const {data:{session}}=await c.auth.getSession();if(session?.user&&String(session.user.email||'').trim().toLowerCase()===OWNER_EMAIL){const name=session.user.user_metadata?.full_name||session.user.user_metadata?.name||'Owner';document.getElementById('ownerPanel').innerHTML=`<div class="ownerAvatar">👑</div><div style="font-weight:800;text-align:center;margin:8px 0;font-size:20px">${name}</div><div class="ownerLogged">✅ Google Owner Login ဝင်ထားပြီးပါပြီ<br><span style="font-weight:600">${OWNER_EMAIL}</span></div><button class="ownerLogout" onclick="ownerLogout()">🚪 Owner Logout</button>`;return}document.getElementById('ownerPanel').innerHTML=`<div class="ownerAvatar">👤</div><div style="font-weight:800;text-align:center;margin:8px 0;font-size:20px">Owner Account</div><div class="ownerHint">Google Gmail နဲ့ Owner Login ဝင်ပါ။</div><button class="ownerGoogle" type="button" onclick="ownerGoogleLogin()"><span>🌐</span><span>Continue with Google</span></button><div id="ownerLoginMsg" class="ownerHint" style="margin-top:10px"></div>`}catch(e){showMsg('<div class="ownerError">❌ Owner Login စစ်ဆေးရာမှာ ပြဿနာရှိပါတယ်။</div>')}}
function addMenu(){const drawer=document.querySelector('.drawer');if(!drawer||drawer.dataset.ownerReady)return;const b=document.createElement('button');b.className='mi ownerBtn';b.type='button';b.innerHTML='👑 Owner Data';b.onclick=function(){if(typeof closeMenu==='function')closeMenu();openOwnerData()};drawer.insertBefore(b,drawer.lastElementChild);drawer.dataset.ownerReady='1'}
async function boot(){style();startTextCleaner();loadLiveShare();loadEnhancements();loadViewNotifications();loadOwnerNotificationRepair();await loadSupabase().catch(()=>null);const ok=await handleOwnerOAuthReturn();addMenu();const menu=document.getElementById('menu');if(menu)new MutationObserver(()=>setTimeout(addMenu,0)).observe(menu,{childList:true,subtree:true});if(ok)setTimeout(()=>openOwnerData(),250)}
window.openOwnerData=openOwnerData;window.closeOwnerData=closeOwnerData;window.ownerGoogleLogin=ownerGoogleLogin;window.ownerLogout=ownerLogout;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
