(function(){
'use strict';
const SUPABASE_URL='https://lsnmcdzupctwizxldjhc.supabase.co';
const SUPABASE_KEY='sb_publishable_iJQ9BpS19OtdaYXM31J3ag_Mhljn8Xi';
const OWNER_TABLE='owner_data';
const OWNER_EMAIL='1987zinwaimin@gmail.com';
const PROD_URL='https://salary-website-chi.vercel.app/';
const EMAIL_COOLDOWN_MS=40000;
let sb=null;
function ensureSupabase(){if(window.supabase&&window.supabase.createClient){if(!sb)sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sb}return null}
function loadSupabase(){if(document.getElementById('supabaseOwnerSdk'))return;const s=document.createElement('script');s.id='supabaseOwnerSdk';s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.async=true;s.onload=()=>{ensureSupabase();syncOwnerFromCloud()};document.head.appendChild(s)}
async function currentUser(){const c=ensureSupabase();if(!c)return null;const {data}=await c.auth.getUser();const u=data?.user||null;if(!u||String(u.email||'').toLowerCase()!==OWNER_EMAIL)return null;return u}
async function getOwner(){const c=ensureSupabase(),u=await currentUser();if(!c||!u)return{};const {data}=await c.from(OWNER_TABLE).select('owner_name,owner_email,avatar_url,created_at,updated_at').eq('user_id',u.id).maybeSingle();if(data)return data;return{owner_email:OWNER_EMAIL,owner_name:u.user_metadata?.full_name||u.user_metadata?.name||'',avatar_url:u.user_metadata?.avatar_url||u.user_metadata?.picture||''}}
async function saveCloudOwner(){const c=ensureSupabase(),u=await currentUser();if(!c||!u)throw new Error('Owner Gmail 1987zinwaimin@gmail.com ဖြင့် Login ဝင်ထားခြင်းမရှိသေးပါ');const meta=u.user_metadata||{};const row={user_id:u.id,owner_name:meta.full_name||meta.name||'Owner',owner_email:OWNER_EMAIL,avatar_url:meta.avatar_url||meta.picture||'',updated_at:new Date().toISOString()};const {error}=await c.from(OWNER_TABLE).upsert(row,{onConflict:'user_id'});if(error)throw error;return row}
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}
function style(){if(document.getElementById('ownerDataStyle'))return;const s=document.createElement('style');s.id='ownerDataStyle';s.textContent='.ownerBtn{background:linear-gradient(135deg,#fff7e8,#fff)!important;border:1px solid #f1dfb5!important}.ownerCard{background:#fff;border-radius:22px;padding:18px;box-shadow:0 12px 30px #34217a14}.ownerAvatar{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#f0eaff;font-size:28px;margin:auto;overflow:hidden}.ownerAvatar img{width:100%;height:100%;object-fit:cover}.ownerEmail{font-weight:800;text-align:center;margin:8px 0}.ownerHint{font-size:11px;color:#71809a;line-height:1.45}.ownerField{width:100%;padding:12px 13px;border:1px solid #dfe3ef;border-radius:13px;background:#fff;outline:0;margin-top:8px}.emailBtn{width:100%;padding:12px;border-radius:13px;background:linear-gradient(135deg,#6948ff,#9a4dff);color:#fff;font-weight:800;margin-top:9px}.emailBtn:disabled{opacity:.55}.ownerDanger{width:100%;padding:11px;border-radius:12px;background:#ffe7eb;color:#d83d54;font-weight:800;margin-top:9px}.cloudBadge{display:inline-block;margin:7px auto 0;padding:5px 9px;border-radius:99px;background:#e8f8f0;color:#16805a;font-size:10px;font-weight:800}.ownerLoading{text-align:center;color:#71809a;font-size:12px;padding:8px}.ownerSuccess{padding:10px;border-radius:12px;background:#e8f8f0;color:#16805a;font-size:12px;font-weight:700;margin-top:9px;text-align:center}.ownerError{padding:10px;border-radius:12px;background:#ffe7eb;color:#d83d54;font-size:12px;font-weight:700;margin-top:9px}.cooldown{margin-top:8px;text-align:center;color:#71809a;font-size:11px;font-weight:700}';document.head.appendChild(s)}
async function openOwnerData(){const m=document.getElementById('modal');if(!m)return;m.className='modal';m.classList.remove('hidden');m.innerHTML='<div class="sheet"><div class="sheethead"><h2>👑 Owner Data</h2><button class="close" onclick="closeOwnerData()">×</button></div><div class="ownerCard"><div class="ownerLoading">☁️ Cloud Data စစ်နေသည်...</div></div></div>';const o=await getOwner();const logged=!!o.owner_email;const avatar=o.avatar_url?'<img src="'+esc(o.avatar_url)+'">':'👤';m.querySelector('.ownerCard').innerHTML='<div class="ownerAvatar">'+avatar+'</div><div class="ownerEmail">'+(logged?esc(OWNER_EMAIL):'Owner Gmail Login မဝင်ရသေးပါ')+'</div>'+(logged?'<div style="text-align:center"><span class="cloudBadge">☁️ Owner • Cloud Saved</span></div>':'<input id="ownerEmailInput" class="ownerField" type="email" value="'+OWNER_EMAIL+'" readonly><button id="ownerEmailBtn" class="emailBtn" onclick="ownerEmailLogin()">✉️ '+OWNER_EMAIL+' နဲ့ Owner Login ဝင်မည်</button><div id="ownerCooldown" class="cooldown hidden"></div>')+'<div id="ownerLoginMsg" class="ownerHint" style="margin-top:10px">'+(logged?'ဒီ Gmail ကို Owner အဖြစ် သတ်မှတ်ထားပြီး Owner Data ကို Supabase Cloud Database ထဲမှာ သိမ်းထားပါတယ်။':'ဒီ Website မှာ Owner အဖြစ် သတ်မှတ်ထားသော Gmail တစ်ခုတည်းက <b>'+OWNER_EMAIL+'</b> ဖြစ်ပါတယ်။ အခြား Gmail ဖြင့် Owner Login မဝင်နိုင်ပါ။')+'</div>'+(logged?'<button class="ownerDanger" onclick="ownerLogout()">🚪 Owner Logout</button>':'')}
function closeOwnerData(){const m=document.getElementById('modal');if(m){m.classList.add('hidden');m.innerHTML=''}}
function startCooldown(){const btn=document.getElementById('ownerEmailBtn'),box=document.getElementById('ownerCooldown');const until=Date.now()+EMAIL_COOLDOWN_MS;sessionStorage.setItem('ownerEmailCooldown',String(until));if(!btn||!box)return;box.classList.remove('hidden');btn.disabled=true;const tick=()=>{const left=Math.max(0,Number(sessionStorage.getItem('ownerEmailCooldown')||0)-Date.now());if(left<=0){btn.disabled=false;box.classList.add('hidden');box.textContent='';return}box.textContent='⏱️ နောက်တစ်ကြိမ် Login Link တောင်းရန် '+Math.ceil(left/1000)+' စက္ကန့်စောင့်ပါ';setTimeout(tick,1000)};tick()}
function restoreCooldown(){const until=Number(sessionStorage.getItem('ownerEmailCooldown')||0);if(until>Date.now())startCooldown();else sessionStorage.removeItem('ownerEmailCooldown')}
async function ownerEmailLogin(){try{const c=ensureSupabase();if(!c){alert('Cloud service မတက်သေးပါ။ ခဏစောင့်ပြီး ပြန်နှိပ်ပါ။');return}const until=Number(sessionStorage.getItem('ownerEmailCooldown')||0);if(until>Date.now()){restoreCooldown();return}const email=OWNER_EMAIL;const msg=document.getElementById('ownerLoginMsg');if(msg)msg.innerHTML='⏳ '+OWNER_EMAIL+' သို့ Owner Login Link ပို့နေသည်...';const {error}=await c.auth.signInWithOtp({email,options:{emailRedirectTo:PROD_URL,shouldCreateUser:true}});if(error)throw error;if(msg)msg.innerHTML='<div class="ownerSuccess">✅ Owner Login Link ပို့ပြီးပါပြီ။ '+OWNER_EMAIL+' Gmail ထဲက အသစ်ဆုံး Link ကိုနှိပ်ပါ။</div>';startCooldown()}catch(e){const msg=document.getElementById('ownerLoginMsg');const text=String(e.message||e);if(msg){if(/36 seconds|after 36|rate limit|rate_limit/i.test(text)){msg.innerHTML='<div class="ownerError">⏱️ Login Link ကို မကြာခဏတောင်းထားလို့ ခဏစောင့်ရပါမယ်။ 36–40 စက္ကန့်လောက်စောင့်ပြီး ပြန်နှိပ်ပါ။</div>';startCooldown()}else msg.innerHTML='<div class="ownerError">❌ Owner Login မအောင်မြင်ပါ: '+esc(text)+'</div>'}}}
async function syncOwnerFromCloud(){try{const c=ensureSupabase();const {data}=c?await c.auth.getUser():{data:null};const u=data?.user||null;if(u&&String(u.email||'').toLowerCase()===OWNER_EMAIL)await saveCloudOwner()}catch(e){console.warn('Owner cloud sync',e)}}
async function ownerLogout(){try{const c=ensureSupabase();if(c)await c.auth.signOut();closeOwnerData();alert('Owner Logout လုပ်ပြီးပါပြီ။')}catch(e){alert('Logout မအောင်မြင်ပါ')}}
function addMenu(){const drawer=document.querySelector('.drawer');if(!drawer||drawer.dataset.ownerReady)return;const b=document.createElement('button');b.className='mi ownerBtn';b.type='button';b.innerHTML='👑 Owner Data';b.onclick=function(){closeMenu();openOwnerData()};drawer.insertBefore(b,drawer.lastElementChild);drawer.dataset.ownerReady='1'}
function boot(){style();loadSupabase();addMenu();const menu=document.getElementById('menu');if(menu)new MutationObserver(()=>setTimeout(addMenu,0)).observe(menu,{childList:true,subtree:true});setTimeout(restoreCooldown,200)}
window.openOwnerData=openOwnerData;window.closeOwnerData=closeOwnerData;window.ownerEmailLogin=ownerEmailLogin;window.ownerLogout=ownerLogout;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
